DemosBlogBundle:
    resource: "@DemosBlogBundle/Controller/"
    type:     annotation
    prefix:   /my

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
